version: '3.1'
services:
  db:
    image: library/postgres:13
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 6543:5432
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8008:8080
    networks:
      - app-network
  web:
    build: './docker/nginx'
    ports:
      - 8000:80
    volumes:
      - ./:/web
      - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    links:
      - php:php
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
  php:
    build: './docker/php'
    restart: always
    links:
      - db:db
    volumes:
      - ./:/web
      - ~/.composer/7.4:/root/.composer
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
